version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    image: exam-backend
    container_name: backend
    command: "php artisan serve --host=0.0.0.0 --port=8080"
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: exam_db
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local