version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
      - db

  backend:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    image: exam-backend
    container_name: backend
    restart: always
    command: "php artisan serve --host=0.0.0.0 --port=8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: exam-frontend
    container_name: frontend
    command: "npm run serve"
    networks:
      - app-network

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exam_db
    volumes:
      - database:/var/lib/mysql
    networks:
      - app-network

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database:
    driver: local