@extends('layouts.email')
@section('title')
    @lang('email_subjects.declineRegistrationOnExam')
@endsection
@section('subtitle')
    @lang('email_messages.hello')!
@endsection
@section('content')
    <p>@lang('email_messages.declineRegistrationOnExam.p1')</p>
    <p>@lang('email_messages.declineRegistrationOnExam.p2')</p>
    <p>@lang('email_messages.declineRegistrationOnExam.p3')</p>
@endsection
