<?php


namespace Tests\Feature\Middleware;


use App\Domains\Auth\Auth;
use App\ExamSession;
use App\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ExamInProgressMiddlewareTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var User
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp();

        $this->user = factory(User::class)->create([
            'exam_datetime' => Carbon::now()->toDateTimeString(),
            'exam_location' => 'testAddress'
        ]);

        Auth::authorizeByEmail($this->user->email);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        Auth::deleteAuthUser();
    }

    public function testExamIsNotProgress()
    {
        $response = $this->get('test/progress');

        $response->assertStatus(400)
            ->assertJson([
                'error' => [
                    'code' => 403,
                ]
            ]);
    }

    public function testExamInProgress()
    {
        factory(ExamSession::class)->create([
            'user_id' => $this->user->id,
            'finished_at' => null
        ]);

        $response = $this->get('test/progress');

        $response->assertStatus(200);
    }
}
